---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  pre_tasks:
    - name: 'oh-my-zsh: get status'
      register: oh_my_zsh
      stat: path=~/.oh-my-zsh/
    - name: 'oh-my-zsh: install'
      shell: curl -L http://install.ohmyz.sh | sh
      when: oh_my_zsh.stat.exists == false

  tasks:
    - name: Update homebrew
      homebrew: update_homebrew=yes

    - name: Add homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/versions
        - tkengo/highway
        - neovim/neovim
        - caskroom/cask

    - name: Install homebrew packages
      homebrew: name={{ item }}
      with_items:
        - rbenv
        - ruby-build
        - go
        - lua
        - tmux
        - reattach-to-user-namespace
        - z
        - nodebrew
        - tig
        - jq
        - ctags
        - highlight
        - imagemagick
        - git-flow
        - gawk
        - gnu-sed
        - docker
        - boot2docker
        - tree
        - graphviz
        - wget
        - cmake
        - git
        - readline
        - python3
        - pyenv
        - highway
        - libmagic
        - opam
        - rlwrap
        - neovim

    - name: Install cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - iterm2
        - java
        - virtualbox
        - vagrant
        - flux
        - dash
        - atom

    - name: 'make symlinks to under home dir'
      file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
      with_fileglob:
        - home_symlinks/*
        - home_symlinks_osx/*

    - name: mkdir vim backup dir
      file: path=~/.vim-backup state=directory

    - name: mkdir XDG_CONFIG_HOME & nvim
      file: path=~/.config/nvim state=directory

    - name: prepare dein.vim installer
      command: curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > _neovim_installer.sh
      when: test -d ${HOME}/.config/nvim

    - name: install dein.vim
      command: sh ./_neovim_installer.sh
      when: test -d ${HOME}/.config/nvim

    - name: remove dein.vim installer
      command: rm ./_neovim_installer.sh
      when: test -b ./_neovim_installer.sh

    - name: make symlinks for neo vim setting
      file: src=~/.vimrc dest=~/.config/nvim/init.vim state=link force=yes

    - name: check go modules status
      command: go list {{ item }}
      register: go_module
      failed_when: go_module.rc not in [0, 1]
      changed_when: go_module.rc not in [0, 1]
      with_items:
        - github.com/motemen/ghq
        - github.com/lestrrat/peco/cmd/peco/

    - name: install go modules
      command: go get {{ item.item }}
      when: item.rc == 1
      with_items: go_module.results

    - name: install opam modules
      command: opam install {{ item }}
      with_items:
        - merlin
        - ocp-indent

  handlers:
    - name: install neobundle
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
