---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  pre_tasks:
    - name: 'oh-my-zsh: get status'
      register: oh_my_zsh
      stat: path=~/.oh-my-zsh/
    - name: 'oh-my-zsh: install'
      shell: curl -L http://install.ohmyz.sh | sh
      when: oh_my_zsh.stat.exists == false

  tasks:
    - name: Update homebrew
      homebrew: update_homebrew=yes

    - name: Add homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/versions
        - tkengo/highway
        - neovim/neovim
        - caskroom/cask
        - sanemat/font

    - name: Install homebrew packages
      homebrew: name={{ item }}
      with_items:
        - rbenv
        - ruby-build
        - go
        - lua
        - tmux
        - reattach-to-user-namespace
        - z
        - nodebrew
        - tig
        - jq
        - ctags
        - highlight
        - imagemagick
        - git-flow
        - gawk
        - gnu-sed
        - tree
        - graphviz
        - wget
        - cmake
        - git
        - readline
        - python3
        - pyenv
        - highway
        - libmagic
        - opam
        - rlwrap
        - neovim
        - peco
        - ricty

    - name: Install cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - iterm2
        - java
        - virtualbox
        - vagrant
        - flux
        - atom
        - hammerspoon

    - name: 'make symlinks to under home dir'
      file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
      with_fileglob:
        - home_symlinks/*
        - home_symlinks_osx/*
        - hammerspoon

    - name: mkdir vim backup dir
      file: path=~/.vim-backup state=directory

    - name: mkdir XDG_CONFIG_HOME & nvim
      file: path=~/.config/nvim state=directory

    - name: check existing neovim path
      command: test -d ${HOME}/.config/nvim
      register: exists_neovim_path
      ignore_errors: True

      # - name: prepare for dein.vim installer
      # - command: curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > _neovim_installer.sh
      # - when: exists_neovim_path

      # - name: install dein.vim
      # - command: sh ./_neovim_installer.sh ${HOME}/.config/nvim
      # - when: exists_neovim_path

      # - name: remove dein.vim installer
      # - command: rm ./_neovim_installer.sh
      # - when: exists_neovim_path

    - name: make symlinks for neovim setting
      file: src=~/.vimrc dest=~/.config/nvim/init.vim state=link force=yes

    - name: install go modules
      command: go get {{ item }}
      with_items:
        - github.com/motemen/ghq

    - name: install opam modules
      command: opam install {{ item }}
      with_items:
        - merlin
        - ocp-indent
