---
- hosts: 127.0.0.1

  pre_tasks:
    - name: 'oh-my-zsh: get status'
      register: oh_my_zsh
      stat: path=~/.oh-my-zsh/
    - name: 'oh-my-zsh: install'
      shell: curl -L http://install.ohmyz.sh | sh
      when: oh_my_zsh.stat.exists == false

  tasks:
    - name: 'make symlinks to under home dir'
      become: yes
      file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
      with_fileglob:
        - home_symlinks/*
        - home_symlinks_ubuntu/*
    - name: Apt install some packages
      apt: pkg={{item}} force=yes update_cache=yes
      with_items:
        - zsh
        - git
        - tmux
        - vim-gnome
        - xsel
        - vim-gtk
    - name: mkdir vim backup dir
      file: path=~/.vim-backup state=directory
    - name: mkdir vim-neobundle dir
      file: path=~/.vim/bundle state=directory
      notify: install neobundle
  handlers:
    - name: install neobundle
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
