---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_packages_taps:
      - homebrew/versions
      - tkengo/highway
      - neovim/neovim
    homebrew_packages_packages:
      - { name: rbenv }
      - { name: ruby-build }
      - { name: go }
      - { name: lua }
      - { name: vim, install_options: with-lua }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: z }
      - { name: nodebrew }
      - { name: tig }
      - { name: jq }
      - { name: ctags }
      - { name: highlight }
      - { name: imagemagick }
      - { name: git-flow }
      - { name: gawk }
      - { name: gnu-sed }
      - { name: docker }
      - { name: boot2docker }
      - { name: tree }
      - { name: graphviz }
      - { name: wget }
      - { name: cmake }
      - { name: git }
      - { name: readline }
      - { name: python3 }
      - { name: pyenv }
      - { name: highway }
      - { name: libmagic }
      - { name: opam }
      - { name: rlwrap }
      - { name: neovim }

    homebrew_cask_packages_packages:
      - iterm2
      - java
      - dropbox
      - virtualbox
      - vagrant
      - karabiner
      - flux
      - pandoc
      - dash
      - atom

  pre_tasks:
    - name: 'oh-my-zsh: get status'
      register: oh_my_zsh
      stat: path=~/.oh-my-zsh/
    - name: 'oh-my-zsh: install'
      shell: curl -L http://install.ohmyz.sh | sh
      when: oh_my_zsh.stat.exists == false

  tasks:
    - name: 'make symlinks to under home dir'
      file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
      with_fileglob:
        - home_symlinks/*
        - home_symlinks_osx/*

    - name: 'karabiner: make symlink of setting files'
      file: src={{ item }} dest=~/Library/Application\ Support/Karabiner/{{ item | basename }} state=link force=yes
      with_fileglob:
        - Karabiner/*

    - name: mkdir vim backup dir
      file: path=~/.vim-backup state=directory

    - name: mkdir XDG_CONFIG_HOME
      file: path=~/.config state=directory

    - name: prepare dein.vim installer
      command: curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > _neovim_installer.sh
      when: test -d ~/.config/nvim

    - name: install dein.vim
      command: sh ./_neovim_installer.sh
      when: test -d ~/.config/nvim

    - name: remove dein.vim installer
      command: rm ./_neovim_installer.sh
      when: test -b ./_neovim_installer.sh

    - name: make symlinks for neo vim setting
      file: src=~/.vimrc dest=~/.config/nvim/init.vim state=link force=yes

    - name: check go modules status
      command: go list {{ item }}
      register: go_module
      failed_when: go_module.rc not in [0, 1]
      changed_when: go_module.rc not in [0, 1]
      with_items:
        - github.com/motemen/ghq
        - github.com/lestrrat/peco/cmd/peco/

    - name: install go modules
      command: go get {{ item.item }}
      when: item.rc == 1
      with_items: go_module.results

    - name: install opam modules
      command: opam install {{ item }}
      with_items:
        - merlin
        - ocp-indent

  handlers:
    - name: install neobundle
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

  roles:
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
